name: travel_food
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  animated_text_kit: ^2.0.0
  bottom_navy_bar: ^5.3.2
  cloud_firestore: ^0.14.1+3
  firebase_core : ^0.5.0
  google_place: ^0.3.3
  restcountries: ^0.0.3
  flutter_dotenv: ^5.0.2
  firebase_auth: ^0.18.4+1
  firebase_dynamic_links: ^0.6.3
  shared_preferences: ^0.5.0
  firebase_storage: ^5.2.0
  image_picker: ^0.6.7+22
  path: ^1.8.0
  sliding_up_panel: ^2.0.0+1
  pull_to_refresh: ^2.0.0
  uuid: ^2.2.2
  flutter_launcher_icons: ^0.8.1
  material_dialogs: ^0.1.4
  google_maps_flutter: ^1.2.0
  flutter_polyline_points: ^0.2.4
  geolocator: ^6.2.1
  flutter_rating_bar: ^4.0.1
  file_picker: 2.0.7
  dynamic_theme: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/mainIcon.png"
  android: true
  ios: true

flutter:

  uses-material-design: true
  assets:
    - assets/one.png
    - assets/two.png
    - assets/three.png
    - assets/home1.jpg
    - assets/hotel.jpg
    - assets/ibis.jpg
    - assets/Meridien.jpg
    - assets/sheraton.jpg
    - assets/alger.jpg
    - assets/bedjaia.jpg
    - assets/tlemcen.jpg
    - assets/adrar.jpg
    - assets/plazamap.png
    - assets/orangeProfile.png
    - assets/orangeProfileTwo.png
    - assets/icon.png
    - assets/mainIcon.png
    - assets/kku-logo.jpeg

  fonts:
    - family: nunito
      fonts:
        - asset: fonts/nunito/Nunito-Black.ttf
        - asset: fonts/nunito/Nunito-Bold.ttf
        - asset: fonts/nunito/Nunito-Regular.ttf
        - asset: fonts/nunito/Nunito-Light.ttf
